security:
    encoders:
        Common\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_EDITOR:      ROLE_USER
        ROLE_ADMIN:       [ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_EDITOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        blog_users:
            entity:
                class: CommonUserBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        blog_security:
            switch_user: true
            pattern:  ^/
            anonymous: ~
            form_login:
                check_path: _check_path
                login_path: blog_login
                default_target_path: blog_index
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path: _logout
                target: blog_index
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
                remember_me_parameter: login[remember_me]

    access_control:
        - { path: ^/account-settings , roles: ROLE_USER }
        - { path: ^/admin-panel, roles: ROLE_EDITOR }
